angular.module("lucidIcons", [])
    .factory('lucidIconFactory', function() {

        var icons = [{
            "icongroup": "22px Icons",
            "icons": [{
                'name': 'icon-add-row-22px'
            }, {
                'name': 'icon-alarm-22px'
            }, {
                'name': 'icon-alert-circle-22px'
            }, {
                'name': 'icon-alert-triangle-22px'
            }, {
                'name': 'icon-align-bottom-22px'
            }, {
                'name': 'icon-align-horizontal-22px'
            }, {
                'name': 'icon-align-left-22px'
            }, {
                'name': 'icon-align-right-22px'
            }, {
                'name': 'icon-align-top-22px'
            }, {
                'name': 'icon-align-vertical-22px'
            }, {
                'name': 'icon-angular-22px'
            }, {
                'name': 'icon-arrow-22px'
            }, {
                'name': 'icon-atlassian-22px'
            }, {
                'name': 'icon-person-22px'
            }, {
                'name': 'icon-person-alert-22px'
            }, {
                'name': 'icon-bell-22px'
            }, {
                'name': 'icon-border-options-22px'
            }, {
                'name': 'icon-briefcase-22px'
            }, {
                'name': 'icon-calendar-22px'
            }, {
                'name': 'icon-camera-22px'
            }, {
                'name': 'icon-check-circle-22px'
            }, {
                'name': 'icon-clock-fill-22px'
            }, {
                'name': 'icon-clock-outline-22px'
            }, {
                'name': 'icon-cloud-22px'
            }, {
                'name': 'icon-comment-22px'
            }, {
                'name': 'icon-comment-alert-22px'
            }, {
                'name': 'icon-comment-outline-22px'
            }, {
                'name': 'icon-compass-22px'
            }, {
                'name': 'icon-computer-desktop-22px'
            }, {
                'name': 'icon-crop-22px'
            }, {
                'name': 'icon-distribute-horizontal-22px'
            }, {
                'name': 'icon-distribute-vertical-22px'
            }, {
                'name': 'icon-dropbox-22px'
            }, {
                'name': 'icon-ellipses-22px'
            }, {
                'name': 'icon-envelope-22px'
            }, {
                'name': 'icon-facebook-block-22px'
            }, {
                'name': 'icon-fill-gradient-linear-22px'
            }, {
                'name': 'icon-fill-gradient-radial-22px'
            }, {
                'name': 'icon-fill-solid-22px'
            }, {
                'name': 'icon-finger-22px'
            }, {
                'name': 'icon-flickr-22px'
            }, {
                'name': 'icon-flip-horizontal-22px'
            }, {
                'name': 'icon-flip-vertical-22px'
            }, {
                'name': 'icon-folder-22px'
            }, {
                'name': 'icon-folder-person-22px'
            }, {
                'name': 'icon-gear-22px'
            }, {
                'name': 'icon-google-22px'
            }, {
                'name': 'icon-google-drive-22px'
            }, {
                'name': 'icon-graph-22px'
            }, {
                'name': 'icon-grid-22px'
            }, {
                'name': 'icon-html-22px'
            }, {
                'name': 'icon-html5-22px'
            }, {
                'name': 'icon-iconfinder-22px'
            }, {
                'name': 'icon-image-22px'
            }, {
                'name': 'icon-layers-22px'
            }, {
                'name': 'icon-lightning-22px'
            }, {
                'name': 'icon-line-jump-22px'
            }, {
                'name': 'icon-line-options-22px'
            }, {
                'name': 'icon-linepath-90-22px'
            }, {
                'name': 'icon-linepath-curve-22px'
            }, {
                'name': 'icon-linepath-double-22px'
            }, {
                'name': 'icon-linepath-straight-22px'
            }, {
                'name': 'icon-link-22px'
            }, {
                'name': 'icon-location-22px'
            }, {
                'name': 'icon-lucidchart-22px'
            }, {
                'name': 'icon-magnet-22px'
            }, {
                'name': 'icon-note-22px'
            }, {
                'name': 'icon-outline-circle-plus-22px'
            }, {
                'name': 'icon-page-22px'
            }, {
                'name': 'icon-paintbrush-22px'
            }, {
                'name': 'icon-pencil-22px'
            }, {
                'name': 'icon-pin-22px'
            }, {
                'name': 'icon-plus-22px'
            }, {
                'name': 'icon-position-22px'
            }, {
                'name': 'icon-present-22px'
            }, {
                'name': 'icon-help-22px'
            }, {
                'name': 'icon-radius-22px'
            }, {
                'name': 'icon-reload-22px'
            }, {
                'name': 'icon-screen-mode-22px'
            }, {
                'name': 'icon-search-large-22px'
            }, {
                'name': 'icon-search-thin-22px'
            }, {
                'name': 'icon-shadow-22px'
            }, {
                'name': 'icon-sort-22px'
            }, {
                'name': 'icon-stalker-22px'
            }, {
                'name': 'icon-swap-22px'
            }, {
                'name': 'icon-team-22px'
            }, {
                'name': 'icon-text-bottom-spacing-22px'
            }, {
                'name': 'icon-text-indent-left-22px'
            }, {
                'name': 'icon-text-indent-right-22px'
            }, {
                'name': 'icon-text-top-spacing-22px'
            }, {
                'name': 'icon-text-padding-22px'
            }, {
                'name': 'icon-trash-22px'
            }, {
                'name': 'icon-view-grid-large-22px'
            }, {
                'name': 'icon-view-grid-list'
            }, {
                'name': 'icon-view-grid-small-22px'
            }, {
                'name': 'icon-view-list-22px'
            }, {
                'name': 'icon-x-22px'
            }, {
                'name': 'icon-x-circle-22px'
            }, {
                'name': 'icon-youre-a-wizard-harry-22px'
            }, {
                'name': 'icon-zoom-in-22px'
            }, {
                'name': 'icon-zoom-out-22px'
            }, {
                'name': 'icon-lock-locked-22px'
            }, {
                'name': 'icon-lock-unlocked-22px'
            }, {
                'name': 'icon-text-22px'
            }, {
                'name': 'icon-text-bold-22px'
            }, {
                'name': 'icon-text-bottom-center-22px'
            }, {
                'name': 'icon-text-bottom-left-22px'
            }, {
                'name': 'icon-text-bottom-right-22px'
            }, {
                'name': 'icon-text-bullets-22px'
            }, {
                'name': 'icon-text-caps-22px'
            }, {
                'name': 'icon-text-center-center-22px'
            }, {
                'name': 'icon-text-center-left-22px'
            }, {
                'name': 'icon-text-center-right-22px'
            }, {
                'name': 'icon-text-italic-22px'
            }, {
                'name': 'icon-text-options-22px'
            }, {
                'name': 'icon-text-smallcaps-22px'
            }, {
                'name': 'icon-text-strikethrough-22px'
            }, {
                'name': 'icon-text-subscript-22px'
            }, {
                'name': 'icon-text-superscript-22px'
            }, {
                'name': 'icon-text-top-center-22px'
            }, {
                'name': 'icon-text-top-left-22px'
            }, {
                'name': 'icon-text-top-right-22px'
            }, {
                'name': 'icon-text-underline-22px'
            }, {
                'name': 'icon-table-grid-22px'
            }, {
                'name': 'icon-table-grid-column-22px'
            }, {
                'name': 'icon-table-grid-row-22px'
            }, {
                'name': 'icon-page-outline-22px'
            }, {
                'name': 'icon-wand-22px'
            }, {
                'name': 'icon-person-large-22px'
            }, {
                'name': 'icon-page-fit-22px'
            }, {
                'name': 'icon-advanced-colorpicker-22px'
            }, {
                'name': 'icon-download-22px'
            }, {
                'name': 'icon-twitter-22px'
            }, {
                'name': 'icon-linkedin-22px'
            }, {
                'name': 'icon-facebook-22px'
            }, {
                'name': 'icon-microsoft-22px'
            }, {
                'name': 'icon-disk-22px'
            }, {
                'name': 'icon-bucket-22px'
            }, {
                'name': 'icon-eye-22px'
            }, {
                'name': 'icon-eye-slash-22px'
            }, {
                'name': 'icon-star-22px'
            }, {
                'name': 'icon-star-outline-22px'
            }, {
                'name': 'icon-fork-22px'
            }, {
                'name': 'icon-add-person-22px'
            }, {
                'name': 'icon-next-stage-22px'
            }, {
                'name': 'icon-notebook-22px'
            }, {
                'name': 'icon-thumbnail-22px'
            }, {
                'name': 'icon-navigator-22px'
            }, {
                'name': 'icon-shape-data-22px'
            }, {
                'name': 'icon-undo-22px'
            }, {
                'name': 'icon-redo-22px'
            }, {
                'name': 'icon-google-docs-22px'
            }, {
                'name': 'icon-google-sheets-22px'
            }, {
                'name': 'icon-jive-22px'
            }, {
                'name': 'icon-slack-22px'
            }, {
                'name': 'icon-hipchat-22px'
            }, {
                'name': 'icon-microsoft-word-22px'
            }, {
                'name': 'icon-back-to-app-22px'
            }, , {
                'name': 'icon-share-22px'
            }, {
                'name': 'icon-book-22px'
            },  {
                'name': 'icon-office-365-22px'
            }, {
                'name': 'icon-video-22px'
            }, {
                'name': 'icon-drop-22px'
            }, {
                'name': 'icon-themes-22px'
            }, {
                'name': 'icon-cloud-outline-22px'
            }, {
                'name': 'icon-diagram-shapes-22px'
            }, {
                'name': 'icon-visio-22px'
            }, {
                'name': 'icon-chat-22px'
            }, {
                'name': 'icon-shape-options-22px'
            }, {
                'name': 'icon-wrench-22px'
            }, {
                'name': 'icon-in-22px'
            }, {
                'name': 'icon-out-22px'
            }, {
                'name': 'icon-add-box-22px'
            }, {
                'name': 'icon-box-22px'
            }]
        }, {
            "icongroup": "18px Icons",
            "icons": [{
                "name": "icon-chevron-18px"
            }, {
                "name": "icon-check-18px"
            }, {
                "name": "icon-gear-18px"
            }, {
                "name": "icon-navigator-18px"
            }, {
                "name": "icon-pencil-18px"
            }, {
                "name": "icon-plus-18px"
            }, {
                "name": "icon-minus-18px"
            }, {
                "name": "icon-search-18px"
            }, {
                "name": "icon-x-18px"
            }, {
                "name": "icon-page-landscape-18px"
            }, {
                "name": "icon-page-portrait-18px"
            }, {
                "name": "icon-lock-unlocked-18px"
            }, {
                "name": "icon-lock-locked-18px"
            }, {
                "name": "icon-triangle-right-18px"
            }, {
                "name": "icon-triangle-down-18px"
            }, {
                "name": "icon-person-18px"
            }, {
                "name": "icon-stage-18px"
            }, {
                "name": "icon-phone-18px"
            }, {
                "name": "icon-clock-medium-18px"
            }, {
                "name":"icon-double-arrow-18px"
            }]
        }];
        return icons;
    });